### ISSUE TITLE
DB collections Relation Not correct

### ISSUE THREAD

**Issue by jaypatel31** [drs1951/CSC510_Group31#15]
**Describe the bug**
In many cases, the DB collection relationship is not properly established, in some places in place of the id, the restaurant name is considered as a foreign key

**Expected behavior**
To establish proper relationships between all collections and make the id of the collection as foreign key for other collections.

**Comment by drs1951** [comment]
The issue has been resolved and correct database relations have been established.

[Here](https://github.com/drs1951/86_Backend/pull/2) is the PR.
