### ISSUE TITLE
Link menu item and inventory

### ISSUE THREAD

**Issue by shyamal31** [drs1951/CSC510_Group31#16]
**Describe the solution you'd like**
Create a a link between menu item and inventory so that when a new menu item is created the corresponding inventory items get deducted automatically.

**Comment by drs1951** [comment]
This issue has been resolved.
[Here](https://github.com/drs1951/86_Backend/pull/4) is the PR

**Comment by jaypatel31** [comment]
For the Frontend side this issue was resolved in #18 PR
