### ISSUE TITLE
Profile Picture Not Visible

### ISSUE THREAD

**Issue by drs1951** [drs1951/CSC510_Group31#2]
**Describe the bug**
On the dashboard, the user profile picture does not load.

**To Reproduce**
1. Login with your credentials.
2. Go to the home page.
3. Check the navbar at the top right corner.
4. The user profile picture will not load.

**Expected behavior**
Profile picture or a placeholder should be visible.

**Comment by shyamal31** [comment]
This issue has been resolved.
[Here](https://github.com/drs1951/CSC510_Group31/pull/20) is the pull request.

**Comment by shyamal31** [comment]
This issue has been resolved.
[Here](https://github.com/drs1951/CSC510_Group31/pull/20) is the pull request.
