### ISSUE TITLE
Add New Analytics Tab

### ISSUE THREAD

**Issue by jaypatel31** [drs1951/CSC510_Group31#21]
**Describe the solution you'd like**
Create a New Page for analytics purposes.

**Additional context**
For now, show the Total sales for each menu item in the last 7 days and also the total usage of inventory items in the last 7 days to help, restaurant owner to make informed decision and plan for next week accordingly.

**Comment by jaypatel31** [comment]
Frontend Done, please review: #22 

@drs1951  please complete the backend request and let me know, so we can merge and make it fully working.

Thanks
Jay

**Comment by drs1951** [comment]
@jaypatel31 APIs have been created. Please review this [PR](https://github.com/drs1951/86_Backend/pull/7).

Thanks
Devansh

**Comment by shyamal31** [comment]
The issue has been resolved. So closing the issue
