### ISSUE TITLE
Incorrect datatype for 'date' attribute  

### ISSUE THREAD

**Issue by shail611** [drs1951/CSC510_Group31#7]
**Describe the bug**
The database has an attribute 'date' which has values in the form of dates but is stored in the database as varchar instead of datatype date. The date entered by the user gets stored in the form of a string instead of a date which can be harmful for the coder who is working on the dates field and is unaware of this

**To Reproduce**
1. Alter the table in the database 
2. Change datatype from varchar to date

**Expected behavior**
Date stored in the form of date and not a string or varchar

**Comment by drs1951** [comment]
Made the necessary changes and the issue is now resolved.
[Here](https://github.com/drs1951/86_Backend/pull/2) is the PR.
